#server:
#  port: 8081
#spring:
#  application:
#    name: nutritionist-service
#  datasource:
#    url: jdbc:postgresql://localhost:5432/nutritionist-service
#    username: postgres
#    password: 123
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    database: postgresql
#    hibernate:
#      ddl-auto: update
#    generate-ddl: true
#    show-sql: true
#    properties:
#      hibernate:
#        jdbc:
#          lob:
#            non_contextual_creation: true
#  config:
#    import:
#      optional:configserver:http://localhost:9196